#!/usr/bin/env fish

source ~/lab/scripts/calls/sourceall

# go to the directory first
cd "$argv[1]"
# capture function call
set functionCall "$argv[2]"
set argv $argv[3..-1]

# assume all the rest are comments
set functionArg ""
while test (count $argv) -gt 0

  set functionArg "$functionArg $argv[1]"
  set argv $argv[2..-1]
  
end

eval "$functionCall '$functionArg'"
