#!/usr/bin/env fish

source ~/lab/scripts/calls/sourceall

# echo "cd into $argv[1]"
# go to the directory first
cd "$argv[1]"
set argv $argv[2..-1]

# call g for status
if test (count $argv) -eq 0
  g 

else
  set functionCall "$argv[1]"
  set argv $argv[2..-1]

  eval "$functionCall $argv"

end
