#!/opt/homebrew/bin/zsh

source ~/lab/scripts/calls/sourceall

# go to the directory first
cd "$1"
shift

# call g for status
if [[ $# == 0 ]]; then
  g 
else
  functionCall="$1"
  shift

  eval "$functionCall \"$@\""
fi
