#!/usr/bin/env fish

source ~/lab/scripts/calls/sourceall

frprepfiles -d $SCREENSHOT_DIRECTORY -t "$(cat $SCREENSHOT_TIME_FILE)" -l -c && \
frprepfiles -d $DOWNLOAD_DIRECTORY -t "$(cat $DOWNLOAD_TIME_FILE)" && \
frprepswift
