#!/opt/homebrew/bin/zsh

source ~/lab/scripts/calls/sourceall

search_query_encoded=$(echo "$@" | sed 's/ /+/g')

open -na "Firefox" --args --private-window "https://duckduckgo.com/?q=$search_query_encoded"

yfocuswin Firefox -title Private
