#!/usr/bin/env fish

source ~/lab/scripts/calls/sourceall

set search_query_encoded $(echo "$argv" | sed 's/ /+/g')

/Applications/Firefox.app/Contents/MacOS/firefox --private-window "https://duckduckgo.com/?q=$search_query_encoded"


yfocuswin Firefox -title Private
