#!/usr/bin/env fish

source ~/lab/scripts/calls/sourceall

set search_query_encoded $(echo "$argv" | sed 's/ /_/g')

/Applications/Firefox.app/Contents/MacOS/firefox --private-window "https://www.powerthesaurus.org/$search_query_encoded/synonyms"
