#!/opt/homebrew/bin/zsh

source ~/lab/scripts/calls/sourceall

set search_query_encoded $(echo "$argv" | sed 's/ /_/g')

open -na "Firefox" --args --private-window "https://www.powerthesaurus.org/$search_query_encoded/synonyms"
