#!/opt/homebrew/bin/zsh
source ~/lab/scripts/calls/sourceall

# go to the directory first
if test (count $argv) -gt 0
  cd "$argv[1]"
  set argv $argv[2..-1]
end

# pass back the levels
gitrootfolder $argv[1]
