#!/opt/homebrew/bin/zsh

source ~/lab/scripts/calls/sourceall

# go to the directory first
cd "$argv[1]"
set argv $argv[2..-1]

# call g for status
if test (count $argv) -eq 0
  g 
else
  functionCall="$1"
  set argv $argv[2..-1]

  eval "$functionCall \"$argv\""
end
