# load last

# alias D='eza -d */; date'
# alias U='eza --grid --all --long --icons --git; date'
# alias o='lsd -a; date'
# alias oo='open .'
# alias u='eza --grid --all --sort=modified --long --icons --git; date'
# alias u='lsd -ltra; date'
alias oo='nvim .'
alias U='eza --all --long --icons --git; date'
alias y='/opt/homebrew/bin/yazi'
alias ls='eza'
alias uu='eza -a; date'
alias u='eza --all --sort=modified --long --icons --git; date'
alias UU='eza --all --sort=modified -1 --icons --git; date'
