# load last
#alias D='eza -d */; date'
alias O='nvim .'
alias ls='eza'
#alias o='lsd -a; date'
alias o='eza -a; date'
#alias oo='open .'
#alias u='lsd -ltra; date'
#alias u='eza --grid --all --sort=modified --long --icons --git; date'
#alias U='eza --grid --all --long --icons --git; date'
alias u='eza --all --sort=modified --long --icons --git; date'
alias U='eza --long --icons --git; date'
