#!/bin/bash


# Function to create a temporary pane
create_temp_pane() {

  pane_id=$(tmux split-window -v -l 30 -d "$1")
  echo $pane_id

}

# Function to close a temporary pane
close_temp_pane() {
    tmux killpane -t $1
}

# Interactive Menu
choice=$(echo -e "default\njot\ntodo\nhtop" | fzf --height 40% --reverse --border)

case $choice in
    "default")
        tmuxdefault=$(ls -1 ~/lab/scripts/tmuxp/ | fzf --height 40% --reverse --border)
        tmuxdefault=$(echo "$tmuxdefault" | sed 's/.yaml//')
        echo "$tmuxdefault" > ~/.tmuxdefault
#        close_temp_pane $pane_id
        exit
        ;;
    "jot")
        jotNotes=$(ls -1 /tmp/nap-* | fzf --height 40% --reverse --border)
        pane_id=$(create_temp_pane "vim $jotNotes")
        ;;
    "todo")
        pane_id=$(create_temp_pane "nvim ~/.todo")
        ;;
    "htop")
        pane_id=$(create_temp_pane "htop")
        ;;
esac

#read -p "Press Enter to close the temporary pane..."
#read "Press Enter to close the temporary pane..."
if [[ $pane_id ]]; then
  close_temp_pane $pane_id
fi
##exit
##tmux kill-window
