[plugin]  

prepend_preloaders = [

  # DB
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
  { mime = "audio/*",   run = "exifaudio"},
  # { mime = "audio/*", run = "audio-preview" },

  # # Office Documents
  # { mime = "application/openxmlformats-officedocument.*", run = "libreoffice" },
  # { mime = "application/oasis.opendocument.*", run = "libreoffice" },
  # { mime = "application/ms-*", run = "libreoffice" },
  # { mime = "application/msword", run = "libreoffice" },
  # { name = "*.docx", run = "libreoffice" },

]

prepend_previewers = [

  # db
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { mime = "audio/*",   run = "exifaudio"},
  # { mime = "audio/*", run = "audio-preview" },
	{ mime = "application/*tar", run = "ouch", multi = false },
  { mime = "application/*gzip", run = "ouch", multi = false },
  { mime = "application/x-bzip*", run = "ouch", multi = false },
  { mime = "application/x-xz", run = "ouch", multi = false },
  { mime = "application/x-zstd", run = "ouch", multi = false },
  { mime = "application/zip", run = "ouch", multi = false },
  { mime = "application/x-7z-compressed", run = "ouch", multi = false },
  { mime = "application/vnd.rar", run = "ouch", multi = false },

  # # Office Documents
  # { mime = "application/openxmlformats-officedocument.*", run = "libreoffice" },
  # { mime = "application/oasis.opendocument.*", run = "libreoffice" },
  # { mime = "application/ms-*", run = "libreoffice" },
  # { mime = "application/msword", run = "libreoffice" },
  # { name = "*.docx", run = "libreoffice" },

]

[mgr]

ratio = [1, 2, 5] # ratio has to equal 8  from the 3 elements that you can have [parent dir, current dir, priview]
sort_by = "mtime"
sort_reverse = true
linemode = "size"
show_hidden = true

[input]
cursor_blink = true

[preview] # preview window
# tab_size = 4
image_quality = 90
max_width = 2000
max_height = 2000
